global using Shouldly;
global using PaintingProjectsManagement.Features.Models;
global using PaintingProjectsManagement.Api;
global using Microsoft.Extensions.DependencyInjection;
global using rbkApiModules.Commons.Testing;
global using rbkApiModules.Identity.Core;
global using System.Net;
global using rbkApiModules.Testting.Core;
global using Microsoft.EntityFrameworkCore;