global using FluentValidation;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.AspNetCore.Routing;
global using Microsoft.AspNetCore.Http;
global using Microsoft.Extensions.DependencyInjection;
global using PaintingProjectsManagement.Features.Materials;
global using PaintingProjectsManagement.Features.Materials.UseCases.Web;
global using rbkApiModules.Commons.Core;
