name: Update Coverage Badge

on:
  workflow_run:
    workflows: [".NET"]
    types:
      - completed

jobs:
  update-badge:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Download coverage artifact
      uses: actions/download-artifact@v4
      with:
        name: coverage-reports
        path: coverage-reports/
    
    - name: Extract coverage percentage
      id: coverage
      run: |
        if [ -f "coverage-reports/Summary.json" ]; then
          COVERAGE_PERCENTAGE=$(jq -r '.summary.linecoverage' coverage-reports/Summary.json)
          echo "coverage_percentage=$COVERAGE_PERCENTAGE" >> $GITHUB_OUTPUT
          echo "Coverage percentage: $COVERAGE_PERCENTAGE%"
        else
          echo "coverage_percentage=0" >> $GITHUB_OUTPUT
          echo "No coverage report found, setting to 0%"
        fi
    
    - name: Generate coverage badge
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        namedLogo: github
        label: coverage
        message: ${{ steps.coverage.outputs.coverage_percentage }}%
        namedLogoColor: white
        color: ${{ steps.coverage.outputs.coverage_percentage >= 80 && 'brightgreen' || steps.coverage.outputs.coverage_percentage >= 60 && 'yellow' || 'red' }}
        namedLogoWidth: 20
        style: flat
        gistID: your-gist-id-here
        filename: coverage-badge.json
